### ISSUE TITLE
[BUG] - vERAM Conversion to Geojson Doesn't Include "Filters" Attribute

### ISSUE THREAD

**Issue by CJP1021** [Nikolai558/FE-BUDDY#114]
When converting a vERAM XML file to Geojson, the Filters attribute doesn't get pulled into the output file. Additionally, sometimes the other attributes aren't included in the output file. 

![Screenshot_1](https://user-images.githubusercontent.com/121987033/210673352-6d91c488-8b47-4d9e-86ca-b75d3842a807.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/121987033/210673362-7524fd66-f4f2-4e24-9068-79301fb3b570.jpg)

**Comment by KSanders7070** [comment]
This was originally coded to include the attributes but by recommendation by the vNAS developers, we decided not to include this because it overrides the attributes assigned to the file as a whole in vNAS. However, in the next update we may include a log that tells you what attributes were assigned to that file within vERAM/vSTARS for quick reference by the user.

**Comment by KSanders7070** [comment]
Further discussion with the OP revealed more clearly that there are times that FEB is actually pulling attributes (such as thickness) at times and exporting it with the GeoJSON. IIRC, this should not be done but there was talk about adding theses attributes if they were found on the actual line (not the defaults) in order to override what is the user-defined default on the vNAS page.
[ZME_GeoMaps.zip](https://github.com/Nikolai558/FE-BUDDY/files/10352498/ZME_GeoMaps.zip)

**Comment by Nikolai558** [comment]
Properties will not be included at all inside the geojson file for VideoMaps or GeoMaps at all now.

Future release will have a log of all the properties for each map in a separate file. 
For Future reference... [Commit where code was fixed](https://github.com/Nikolai558/FE-BUDDY/commit/e8202aa4703f17c5d08c22bfba1a5d1af428b503)

**Comment by Nikolai558** [comment]
Correction: Will add properties to the geojson if they are specified. Even if they are the same as the default. Otherwise it will not add the properties into the geojson. 
This is not yet fully completed or fully tested.

**Comment by Nikolai558** [comment]
This has been resolved and will be included in the next release. 2.3.7

**Comment by Nikolai558** [comment]
https://github.com/Nikolai558/FE-BUDDY/releases/tag/2.3.7
