### ISSUE TITLE
[FEAT REQ.] - STARS map group in JSON filename

### ISSUE THREAD

**Issue by EvermanD** [Nikolai558/FE-BUDDY#124]
Working on getting ZMP's STARS maps converted to JSON at the moment and was wondering if there could be an option to include the map group (A/B) in the filename after exporting with FE-BUDDY. Doing so would be a bit of a QOL improvement so I don't have to open up the .xml or vSTARS to remind myself which group the maps go in with editing them on the vNAS end.

**Comment by KSanders7070** [comment]
Need clarification as to what the output would look like to you?

All files assigned to group A would be in the same file? Essentially creating only two output files for each facility.
-if so, that doesn’t give you much flexibility for editing that data later on.

All files have an indication in the file name of what group, Example: “GROUP-A_MVA”?
-if so, that doesn’t seem to be much of an improvement, as you can easily do a collapse in the .xml and basically get a list of which maps belong to which group.

A log of the group assignments output with the files?
-This would be fairly easy to code but would essentially be the same as you looking at the .xml but in a nicer format.

All files belonging to group A/B would be in a subdirectory labeled with their respective group letter?
Example: FE-Buddy-GeoJSON\MSP\Group A
-I can see this being a little more useful, as you can kinda batch upload that then go through and assign each of the newly uploaded files their defaults.

But, is this that much of a QOL improvement? I am really asking because I only know how easy/hard it was for me to manually do this for all of ZLC but our files are fairly organized and minimal and with that, it took me about 3hrs to do all of my facility vSTARS files by just cross referencing what the .xml says.

Don’t get the impression that we are against doing this, we just want to know exactly what you would like and how many hours of us coding it would it save you?

![image](https://user-images.githubusercontent.com/63331106/213344977-77c58592-59eb-418a-bd05-01893b89eb67.jpeg)

**Comment by EvermanD** [comment]
My idea would have been your second example. Honestly the thought of collapsing the xml totally slipped my mind today. Our maps don't change much, if it all, and aren't projected to in the near future, so once I've got it done I've got it done for a while so don't worry about doing it for me specifically, I guess.

**Comment by KSanders7070** [comment]
Well, I'm going to leave this issue open so we can discuss it more. If it doesn't take much time to code, we may do something like this hopefully in the next update. Just because you are the only one requesting it doesn't mean others wouldn't appreciate the same feature and just haven't requested it. Thanks for submitting this.

**Comment by KSanders7070** [comment]
Closed, as this situation seems to have a practical manual solution.
