### ISSUE TITLE
[BUG] - Missing elements and objects when converting from vERAM geomap.xml to geojson

### ISSUE THREAD

**Issue by DivineWind04** [Nikolai558/FE-BUDDY#148]
**Describe the bug**

**To Reproduce**
1. Import vERAM geomap.xml
2. Select either by filter or description
3. Export

**Expected behavior**
Have all elements and objects exported

**Screenshots**

**Comment by KSanders7070** [comment]
Do you have a source file that you could upload and specify which objects that aren't exporting so we can look into it?

**Comment by DivineWind04** [comment]
https://oakartcc.org/controllers/file/050daacd-4c85-11eb-8d1f-2a32edb55910

Thanks,
Dominic
________________________________

**Comment by KSanders7070** [comment]
We investigated your file and ran both a “GeoMapObject Description” output and a “Filter Index and Similar Attributes” and on the surface, FEB seems to be getting everything.

You say you are missing elements and objects but which ones? Your file is fairly large and map descriptions aren't very well labeled; Help us narrow down the issue?

**Comment by DivineWind04** [comment]
How are you viewing the elements to see if they've been all exported or not? The objects would export but not all the elements are exported out within those object files

Thanks,
Dominic
________________________________

**Comment by KSanders7070** [comment]
We have no automated "test/check" to see if there were any **_legal_** elements not exported _(we plan to have these type of tests in v3.0+)_ because these issues SHOULD have presented themselves while we were coding it; The ZOA file was one of our primary test files we used for testing, so it would have came up then.

A simple test we do can do manually would be compare your source file ZOAHI GeoMap `Object #17 (SupplementalLine)` that has only two line segments to the respective output geoJson file that has both line segments in it...

OBJECT 17 source file:
![OBJECT 17 source file](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/a53bb4e1-eb75-4907-88c3-047131b9148f)

OBJECT 17 output file by Description:
![OBJECT 17 output file by Description](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/c5ac4760-b1c2-455e-b8a6-27e68d2a61e2)

As you can see^, the source file matches the output file.
If you ran the output by filter and other attributes, you can find `Object #17` in the “FILTER 20__TDM F__Line__BCG 20__Filters 20__Style LongDashed__Thickness 1__.geojson” file..

OBJECT 17 output file by Filter:
![OBJECT 17 output file by Filter](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/381bce2c-2382-4de6-ad7c-3df75d71c4d2)

OBJECT 17 output file by Filter Log:
![OBJECT 17 output file by Filter Log](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/d533db82-eb49-4618-9950-e965a9ba2d6c)

...again^, the output matches the source file.

To troubleshoot any missing elements, we first need to know which elements are missing. For example, looking at your ZOAHI Airport Diagrams file and zooming into KSFO, I noticed that one of the taxiways aren't drawn (maybe on purpose, but that doesn't matter). If these taxiway lines were missing, it would be helpful to have a screenshot like the one below as an example of something you are missing. It would also be helpful if you tell us any further information about the missing elements such as which object they are attached to, filter, what it is, coordinates, etc... something to help narrow it down.
![APD missing taxiway](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/67344d04-7bc9-4771-a658-989d33c0869c)

You should also note that if the element line has a “XSI: TYPE” that is not specified in the “Defaults” above the array, it will not be output. However, if that was the case then you likely wouldn't see it in vERAM anyways.
![XSI Type without defined defaults warning](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/f58ee8a7-c81f-4ba7-9090-e857985a7726)

Help us out by telling us exactly what is missing (at least one example) so we can help track down the issue.

**Comment by DivineWind04** [comment]
Check out object#1292 in the NORLOW geomap, the symbols and text make it over, but it’s missing a lot of lines

Thanks,
Dominic
________________________________

**Comment by KSanders7070** [comment]
There does not appear to be an object #1292 in the NORLOW GeoMap.

![image](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/e0eaebd4-ff87-4642-a53b-fce428f1833b)

![image](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/ecb05e5d-0440-4bf4-a0dc-1bf7cbb08dff)

**Comment by DivineWind04** [comment]
Typo. #1192

Thanks,
Dominic
________________________________

**Comment by KSanders7070** [comment]
Possible issue: FEB does not handle identical Object Descriptions well. Researching.

![image](https://github.com/Nikolai558/FE-BUDDY/assets/63331106/6e73c3d6-1a18-4696-9caf-259165732672)

**Comment by Nikolai558** [comment]
Bug verified - Most likely happening with vStars conversions as well.

When FE-Buddy comes across multiple GeoMapObjects with the same exact Description name, the file is created and data is written to it. However, when FE-Buddy comes across the second object (and so on) it overites the .geojson file that it has created for that first object. This leaves the .geojson file with data from the LAST object with that name. 

This should be pretty simple and easy to fix. Expect a fix in the near by future. 

Dev note: 
https://github.com/Nikolai558/FE-BUDDY/blob/1d569d60eddc0b5169dc932cdea04bbac34ff3c7/FeBuddyLibrary/DataAccess/GeoJson.cs#LL1169C25-L1169C36

**Comment by Nikolai558** [comment]
I am assuming this is what the #1192 (tav) is supose to look like:
![image](https://github.com/Nikolai558/FE-BUDDY/assets/38259407/fbd5c85d-2788-4037-b0d6-5d3b17eb00d6)

If so, this bug has been fixed and a release will follow shortly.

**Comment by Nikolai558** [comment]
Unless you find further issues regarding this same topic, I am going to close this issue. Feel free to open it back up if it does not fix all the problems.
