### ISSUE TITLE
[TODO] - Get List of GH Releases Tags

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#35]
**Describe the "TODO"**
The batch script attached will get you a list of all tags on the release page.

Consider using this method to sort them alphanumerically:
https://stackoverflow.com/questions/47529749/sort-alphanumeric-string-containing-decimal-in-c-issue-with-decimal-points?noredirect=1&lq=1

[Get_GH_Version_Numbers_From_Releases.txt](https://github.com/Nikolai558/FE-BUDDY/files/8035967/Get_GH_Version_Numbers_From_Releases.txt)

**Comment by KSanders7070** [comment]
The "@echo off" at the start can also be removed when you are making the program write this batch.

**Comment by KSanders7070** [comment]
Now that I think about it, with the exception of the CURL line, the rest is probably better to be scripted in FE-Buddy, as it handles data parsing better than BATCH.

**Comment by caesay** [comment]
Squirrel is capable of retrieving/parsing all of the releases for the purposes of grabbing the latest delta/full update, and it also supports release notes. It might already do something close to what you're trying to do - if you can describe the purpose of the issue here a bit better I might be able to help.

**Comment by KSanders7070** [comment]
I will let Nik answer officially but he and I have spoken about your updates with squirrel and it seems like yours does a better job of what we were trying to do anyways. This issue might be able to just be closed.
