### ISSUE TITLE
[BUG] - .id commands showing duplicates

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#68]
![Screenshot_2](https://user-images.githubusercontent.com/63331106/180090227-d40285f9-40f2-4060-b51f-5282964dfa92.jpg)

**Comment by Nikolai558** [comment]
![image](https://user-images.githubusercontent.com/38259407/180102452-1d607885-5a93-4d34-9cb2-285f8c08bb07.png)

There are some Telephony names that are only 3 letters long. This is causing the issue for those telephony that have the same 3ld. See example above. 

This has been remidied by putting all the .id commands that use the 3ld at the top of the alias file instead of intertwined with the .id commands that use the name. 99% of the time when a user uses this command they are going to be using the 3ld version of it.
