### ISSUE TITLE
[BUG] - ASDEX Style:Solid

### ISSUE THREAD

**Issue by KSanders7070** [Nikolai558/FE-BUDDY#92]
Only a LINE can be a solid... Not polygon
-Nathan Rankin

**Comment by nrankin18** [comment]
This issue is conflating two issues I saw the following screenshot. The `style` property should be lowercase ("solid"). And there shouldn't ever be a GeoJSON feature with both an `asdex` property (polygons only) and a thickness property (lines only).

https://cdn.discordapp.com/attachments/953725303178534982/1006372218789429309/Screenshot_12.jpg

**Comment by Nikolai558** [comment]
This has been fixed v2.3.1. Asdex/Polygons will no longer have the "thickness" or "style" properties inside the geojson output.
